{
 "title": "Ceph RBD Overview [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_ops{taco_cluster=~'$taco_cluster'}[5m])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_ops{taco_cluster=~'$taco_cluster'}[5m])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_bytes{taco_cluster=~'$taco_cluster'}[5m])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_bytes{taco_cluster=~'$taco_cluster'}[5m])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_latency_sum{taco_cluster=~'$taco_cluster'}[5m])) / sum(irate(ceph_rbd_write_latency_count{taco_cluster=~'$taco_cluster'}[5m])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_latency_sum{taco_cluster=~'$taco_cluster'}[5m])) / sum(irate(ceph_rbd_read_latency_count{taco_cluster=~'$taco_cluster'}[5m])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, (sort((irate(ceph_rbd_write_ops{taco_cluster=~'$taco_cluster'}[5m]) + on(image, pool, namespace) irate(ceph_rbd_read_ops{taco_cluster=~'$taco_cluster'}[5m])))))"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sort(sum(irate(ceph_rbd_read_bytes{taco_cluster=~'$taco_cluster'}[5m]) + irate(ceph_rbd_write_bytes{taco_cluster=~'$taco_cluster'}[5m])) by (pool, image, namespace)))"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    irate(ceph_rbd_write_latency_sum{taco_cluster=~'$taco_cluster'}[5m]) / clamp_min(irate(ceph_rbd_write_latency_count{taco_cluster=~'$taco_cluster'}[5m]), 1) +\n    irate(ceph_rbd_read_latency_sum{taco_cluster=~'$taco_cluster'}[5m]) / clamp_min(irate(ceph_rbd_read_latency_count{taco_cluster=~'$taco_cluster'}[5m]), 1)\n  ) by (pool, image, namespace)\n)"
    }
   ]
  }
 ]
}