{
 "title": "OpenStack Service [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" },
   {
    "name": "region",
    "query": "label_values(openstack_exporter_cache_refresh_duration_seconds, region)"
   }
  ]
 },
 "panels": [
  { "title": "Virtual resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vCPUs ( total vs used )",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(openstack_total_used_vcpus{ region=\"$region\" } + openstack_total_free_vcpus{ region=\"$region\" } )"
    },
    {
     "expr": "openstack_total_used_vcpus{region=\"$region\"}"
    }
   ]
  },
  {
   "title": "RAM ( total vs used )",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(openstack_total_used_ram_MB{region=\"$region\"}+ openstack_total_free_ram_MB{region=\"$region\"})"
    },
    {
     "expr": "openstack_total_used_ram_MB{region=\"$region\"}"
    }
   ]
  },
  {
   "title": "DISK ( total vs used )",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(openstack_total_used_disk_GB{region=\"$region\"}+ openstack_total_free_disk_GB{region=\"$region\"})"
    },
    {
     "expr": "openstack_total_used_disk_GB{region=\"$region\"}"
    }
   ]
  },
  {
   "title": "openstack allocation ratio",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack_allocation_ratio" }
   ]
  },
  { "title": "Openstack service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "neurton",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_check_neutron_api{region=\"$region\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "glance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_check_glance_api{region=\"$region\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "keystone",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_check_keystone_api{region=\"$region\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "placement",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_check_placement_api{region=\"$region\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "cinder",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_check_cinder_api{region=\"$region\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "nova",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_check_nova_api{region=\"$region\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "openstack service alarm",
   "type": "graph",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_services_neutron_dhcp_agent_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "neutron_dhcp_agent_down_total"
    },
    {
     "expr": "openstack_services_neutron_openvswitch_agent_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "neutron_openvswitch_agent_down_total"
    },
    {
     "expr": "openstack_services_neutron_l3_agent_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "neutron_l3_agent_down_total"
    },
    {
     "expr": "openstack_services_neutron_metadata_agent_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "neutron_metadata_agent_down_total"
    },
    {
     "expr": "openstack_services_nova_conductor_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "nova_conductor_down_total"
    },
    {
     "expr": "openstack_services_nova_scheduler_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "nova_scheduler_down_total"
    },
    {
     "expr": "openstack_services_nova_compute_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "nova_compute_down_total"
    },
    {
     "expr": "openstack_services_nova_consoleauth_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "nova_consoleauth_down_total"
    },
    {
     "expr": "openstack_services_cinder_volume_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "cinder_volume_down_total"
    },
    {
     "expr": "openstack_services_cinder_scheduler_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "cinder_scheduler_down_total"
    },
    {
     "expr": "openstack_services_cinder_backup_down_total{region=\"$region\",taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "cinder_backup_down_total"
    }
   ]
  },
  { "title": "Rabbitmq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "rabbitmq health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_up{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "rabbitmq running node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_running{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "rabbitmq messages published",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_published_total{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "rabbitmq messages ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Mariadb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Maria ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_ready{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "Maria Sync",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_local_state{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "Maria Slave",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_slave_running{kubernetes_namespace=\"openstack\",taco_cluster=\"$taco_cluster\"}"
    }
   ]
  }
 ]
}