{
 "title": "Cluster Status [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{taco_cluster=~\"$taco_cluster\", job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 1)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{taco_cluster=~\"$taco_cluster\", alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{taco_cluster=~\"$taco_cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{taco_cluster=~\"$taco_cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\"}) - sum (node_filesystem_free_bytes{taco_cluster=~\"$taco_cluster\"})) / sum (node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  { "title": "Control Plane Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Servers UP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(sum(up{taco_cluster=~\"$taco_cluster\", job=\"apiserver\"} == 1) / count(up{taco_cluster=~\"$taco_cluster\", job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "(sum(up{taco_cluster=~\"$taco_cluster\", job=\"kube-controller-manager\"} == 1) / count(up{taco_cluster=~\"$taco_cluster\", job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "(sum(up{taco_cluster=~\"$taco_cluster\", job=\"kube-scheduler\"} == 1) / count(up{taco_cluster=~\"$taco_cluster\", job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "Control Plane Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{taco_cluster=~\"$taco_cluster\", namespace=~\"kube-system\"}[1h]) > 5)"
    }
   ]
  },
  { "title": "Capacity Planing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(100 - (avg by (instance) (rate(node_cpu_seconds_total{taco_cluster=~\"$taco_cluster\", job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)) / count(node_cpu_seconds_total{taco_cluster=~\"$taco_cluster\", job=\"node-exporter\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{taco_cluster=~\"$taco_cluster\"}) - sum(node_memory_MemFree_bytes{taco_cluster=~\"$taco_cluster\"}) - sum(node_memory_Buffers_bytes{taco_cluster=~\"$taco_cluster\"}) - sum(node_memory_Cached_bytes{taco_cluster=~\"$taco_cluster\"})) / sum(node_memory_MemTotal_bytes{taco_cluster=~\"$taco_cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\", device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{taco_cluster=~\"$taco_cluster\", device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\", device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods{taco_cluster=~\"$taco_cluster\"}) - sum(kube_pod_info{taco_cluster=~\"$taco_cluster\"})) / sum(kube_node_status_capacity_pods{taco_cluster=~\"$taco_cluster\"}) * 100"
    }
   ]
  },
  { "title": "Node Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Unready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=~\"$taco_cluster\", condition=\"Ready\", status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=~\"$taco_cluster\", condition=\"DiskPressure\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Nodes Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=~\"$taco_cluster\", condition=\"MemoryPressure\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Nodes Network Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=~\"$taco_cluster\", condition=\"NetworkUnavailable\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Nodes PID Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=~\"$taco_cluster\", condition=\"PIDPressure\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=~\"$taco_cluster\", condition=\"OutOfDisk\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "format": "none",
   "valueName": "current"
  }
 ]
}