{
 "title": "Compute Resources Cluster [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{taco_cluster=~\"$taco_cluster\", mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers_bytes:sum{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{taco_cluster=~\"$taco_cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  { "title": "CPU / Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{taco_cluster=~\"$taco_cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum{taco_cluster=~\"$taco_cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{taco_cluster=~\"$taco_cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{taco_cluster=~\"$taco_cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{taco_cluster=~\"$taco_cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory / Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{taco_cluster=~\"$taco_cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{taco_cluster=~\"$taco_cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{taco_cluster=~\"$taco_cluster\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{taco_cluster=~\"$taco_cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{taco_cluster=~\"$taco_cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes{taco_cluster=~\"$taco_cluster\"}) by (namespace)"
    }
   ]
  }
 ]
}