{
 "title": "Hosts Status [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Node Status / Up TIme",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_uname_info{taco_cluster=~\"$taco_cluster\"}) by (instance, job, nodename, pod, service, version) "
    },
    {
     "expr": "sum(node_boot_time_seconds{taco_cluster=~\"$taco_cluster\"}) by (instance, job, pod, service)"
    }
   ]
  },
  {
   "title": "Node Utilisation by CPU and RAM requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_memory_bytes{taco_cluster=~\"$taco_cluster\"}) by (node) \n  /\n  sum(kube_node_status_allocatable_memory_bytes{taco_cluster=~\"$taco_cluster\"}) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_cpu_cores{taco_cluster=~\"$taco_cluster\"}) by (node) \n  /\n  sum(kube_node_status_allocatable_cpu_cores) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Disk Space Used Basic(EXT4/XFS)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\", fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes{taco_cluster=~\"$taco_cluster\", fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{taco_cluster=~\"$taco_cluster\", fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\", fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(cadvisor_version_info{taco_cluster=~\"$taco_cluster\"}) by (goversion, instance, job, namespace, pod, revision, service, version)",
     "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
    },
    {
     "expr": "sum(prometheus_build_info{taco_cluster=~\"$taco_cluster\"}) by (goversion, instance, job, namespace, pod, revision, service, version)",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "sum(node_exporter_build_info{taco_cluster=~\"$taco_cluster\"}) by (goversion, instance, job, namespace, pod, revision, service, version)",
     "legendFormat": "Node-Exporter Version: {{version}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(ALERTS{taco_cluster=~\"$taco_cluster\", alertstate=\"firing\"}) by (alertname, alertstate, instance, job, severity)"
    }
   ]
  }
 ]
}