{
 "title": "Ceph Pools Overview [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "taco_cluster", "query": "label_values(up, taco_cluster)" },
   { "name": "topk", "label": "Top K", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Top $topk Client IOPS by Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "topk($topk,rate(ceph_pool_rd{taco_cluster=~'$taco_cluster'}[5m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'}) ",
     "legendFormat": "{{name}} - read"
    },
    {
     "expr": "topk($topk,rate(ceph_pool_wr{taco_cluster=~'$taco_cluster'}[5m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'}) ",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Client Throughput by Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Writes (+)" }
   ],
   "targets": [
    {
     "expr": "topk($topk,rate(ceph_pool_rd_bytes{taco_cluster=~'$taco_cluster'}[5m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'})",
     "legendFormat": "{{name}} - read"
    },
    {
     "expr": "topk($topk,rate(ceph_pool_wr_bytes{taco_cluster=~'$taco_cluster'}[5m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'})",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Pools by Client IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk($topk,((irate(ceph_pool_rd{taco_cluster=~'$taco_cluster'}[5m]) + irate(ceph_pool_wr{taco_cluster=~'$taco_cluster'}[5m])) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'}))"
    }
   ]
  },
  {
   "title": "Top $topk Pools by Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk($topk,(irate(ceph_pool_rd_bytes{taco_cluster=~'$taco_cluster'}[5m]) + irate(ceph_pool_wr_bytes{taco_cluster=~'$taco_cluster'}[5m])) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'}) "
    }
   ]
  },
  {
   "title": "Top $topk Pools By Capacity Used",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "topk($topk,((ceph_pool_stored{taco_cluster=~'$taco_cluster'} / (ceph_pool_stored{taco_cluster=~'$taco_cluster'} + ceph_pool_max_avail{taco_cluster=~'$taco_cluster'})) * on(pool_id) group_left(name) ceph_pool_metadata{taco_cluster=~'$taco_cluster'}))"
    }
   ]
  }
 ]
}