{
 "title": "Node Network Detail [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(node_uname_info{taco_cluster=~\"$taco_cluster\", job=~\"$job\"}, nodename)"
   },
   {
    "name": "server",
    "query": "label_values(node_uname_info{taco_cluster=~\"$taco_cluster\", job=~\"$job\", nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info{taco_cluster=~\"$taco_cluster\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Network Traffic Frame",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_frame_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Receive frame"
    },
    {
     "expr": "irate(node_network_transmit_frame_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} - Transmit frame"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$server\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$server\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "ARP Entries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=~\"$server\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  }
 ]
}