{
 "title": "F5 Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Big IP Controller Utilization & Location",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage (skb-suy-adm01)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{taco_cluster=~\"skb-suy-adm.*\",container=~\"k8s-big.*\",namespace=\"kube-system\",pod=~\"k8s-big.*\"}[1m])",
     "legendFormat": "{{pod}} : {{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage (skb-suy-adm01)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"k8s-bigip.*\", namespace=\"kube-system\",taco_cluster=~\"skb-suy-adm01\",image!=\"\",container!=\"POD\"}",
     "legendFormat": "{{pod}} : {{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage (skb-suy-prod01)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{taco_cluster=~\"skb-suy-prd01.*\",container=~\"k8s-big.*\",namespace=\"kube-system\",pod=~\"k8s-big.*\"}[1m])",
     "legendFormat": "{{pod}} : {{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage (skb-suy-prd01)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"k8s-bigip.*\", namespace=\"kube-system\",taco_cluster=~\"skb-suy-prd01\",image!=\"\",container!=\"POD\"}",
     "legendFormat": "{{pod}} : {{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage (skb-ssu-pro02)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{taco_cluster=~\"skb-ssu-prd02.*\",container=~\"k8s-big.*\",namespace=\"kube-system\",pod=~\"k8s-big.*\"}[1m])",
     "legendFormat": "{{ pod}} : {{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage (skb-ssu-prd02)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"k8s-bigip.*\", namespace=\"kube-system\",taco_cluster=~\"skb-ssu-prd02\",image!=\"\",container!=\"POD\"}",
     "legendFormat": "{{ pod}} : {{node}}"
    }
   ]
  },
  { "title": "F5 Request Per Second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "수유-namespace별 RPS(1분평균)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(f5_pool_member_requests{taco_cluster=~\"skb-suy-prd.*\", namespace=~\"metv|scs|stb|common.*\"}[1m]))by(namespace) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "수유 RPS(30초평균)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(f5_pool_member_requests{taco_cluster=~\"skb-suy-prd.*\", namespace=~\"metv|scs|stb|common.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "성수-namespace별 RPS(1분평균)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(f5_pool_member_requests{taco_cluster=~\"skb-ssu-prd.*\", namespace=~\"metv|scs|stb|common.*\"}[1m]))by(namespace) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "성수 RPS(30초 평균)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(f5_pool_member_requests{taco_cluster=~\"skb-ssu-prd.*\", namespace=~\"metv|scs|stb|common.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "F5 Pool Member Request (metv, scs,  common, stb)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "수유서비스 F5 Pool Member Request (metv, scs, common, stb)-30초 평균",
   "type": "graph",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(f5_pool_member_requests{taco_cluster=~\"skb-suy-prd.*\", namespace=~\"metv|scs|stb|common.*\"}[30s]))by(taco_cluster, svc) ",
     "legendFormat": "{{taco_cluster}}:: {{svc}}"
    }
   ]
  },
  {
   "title": "성수 서비스 F5 Pool Member Request (metv, scs, common, stb)-30초 평균",
   "type": "graph",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(f5_pool_member_requests{taco_cluster=~\"skb-ssu-prd.*\", namespace=~\"metv|scs|stb|common.*\"}[30s]))by(taco_cluster, svc) ",
     "legendFormat": "{{taco_cluster}}:: {{svc}}"
    }
   ]
  }
 ]
}