{
 "title": "Ceph Pool Details [TACO]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "taco_cluster", "query": "label_values(up, taco_cluster)" },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": "label_values(ceph_pool_metadata,name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(ceph_pool_stored{taco_cluster=~'$taco_cluster'} / ceph_pool_max_avail{taco_cluster=~'$taco_cluster'}) * on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}"
    }
   ]
  },
  {
   "title": "Time till full",
   "type": "singlestat",
   "description": "Time till pool is full assuming the average fill rate of the last 6 hours",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "((ceph_pool_max_avail{taco_cluster=~'$taco_cluster'} - ceph_pool_stored{taco_cluster=~'$taco_cluster'}) / deriv(ceph_pool_stored{taco_cluster=~'$taco_cluster'}[6h])) * on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"} > 0"
    }
   ]
  },
  {
   "title": "$pool_name Object In-/Egress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Objects out(-) / in(+) " }
   ],
   "targets": [
    {
     "expr": "deriv(ceph_pool_objects{taco_cluster=~'$taco_cluster'}[5m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}",
     "legendFormat": "Objects per second"
    }
   ]
  },
  {
   "title": "$pool_name Client IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{taco_cluster=~'$taco_cluster'}[5m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "irate(ceph_pool_wr{taco_cluster=~'$taco_cluster'}[5m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name Client Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{taco_cluster=~'$taco_cluster'}[5m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{taco_cluster=~'$taco_cluster'}[5m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Objects" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{taco_cluster=~'$taco_cluster'} * on(pool_id) group_left(instance,name) ceph_pool_metadata{taco_cluster=~'$taco_cluster',name=~\"$pool_name\"}",
     "legendFormat": "Number of Objects"
    }
   ]
  }
 ]
}