{
 "title": "Cluster Overview (Total)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "K8s Cluster Health (모든 클러스터)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "수유 서비스 클러스터 노드 갯수",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_created{taco_cluster=~\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "성수 서비스 클러스터 노드 갯수",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_created{taco_cluster=~\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "수유 어드민 클러스터 노드 갯수 ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_created{taco_cluster=~\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "apiserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\", taco_cluster=\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\", taco_cluster=\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{taco_cluster=~\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "apiserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\", taco_cluster=\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\", taco_cluster=\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{taco_cluster=~\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "apiserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\", taco_cluster=\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\", taco_cluster=\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{taco_cluster=~\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "kubelet",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"kubelet\", taco_cluster=\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\", taco_cluster=\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "Coredns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\", taco_cluster=\"skb-suy-prd01\"})"
    }
   ]
  },
  {
   "title": "Kublet",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"kubelet\", taco_cluster=\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\", taco_cluster=\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "Coredns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\", taco_cluster=\"skb-ssu-prd02\"})"
    }
   ]
  },
  {
   "title": "kubelet",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"kubelet\", taco_cluster=\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\", taco_cluster=\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "Coredns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\", taco_cluster=\"skb-suy-adm01\"})"
    }
   ]
  },
  {
   "title": "PODs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{taco_cluster=~\"skb-suy-prd01\", created_by_kind != \"Workflow\"})"
    }
   ]
  },
  {
   "title": "PODs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{taco_cluster=~\"skb-ssu-prd02\", created_by_kind != \"Workflow\"})"
    }
   ]
  },
  {
   "title": "PODs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{taco_cluster=~\"skb-suy-adm01\", created_by_kind != \"Workflow\"})"
    }
   ]
  },
  {
   "title": "Pod 갯수 ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc (count by (node) (kube_pod_info{taco_cluster=\"skb-suy-prd01\", created_by_kind != \"Workflow\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 Liveness",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\",taco_cluster=~\"skb-suy-prd01\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": " Pod 갯수 ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc (count by (node) (kube_pod_info{taco_cluster=\"skb-ssu-prd02\", created_by_kind != \"Workflow\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 Liveness",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\",taco_cluster=~\"skb-ssu-prd02\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod 갯수 ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc (count by (node) (kube_pod_info{taco_cluster=\"skb-suy-adm01\", created_by_kind != \"Workflow\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 Liveness",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\",taco_cluster=~\"skb-suy-adm01\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "클러스터별 K8s System Deployment Health ($taco_cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "List of Deployment",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Desired pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Current pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Desired pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Current pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Available pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Available pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Unavailable pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"kube-system\", taco_cluster=\"$taco_cluster\"}  ",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "클러스터별 K8s Cluster Resource Usage ($taco_cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Sum CPU requests per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests_cpu_cores{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum CPU allocatable per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_allocatable_cpu_cores{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum Memory requests per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests_memory_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum Memory allocatable per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_allocatable_memory_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}