{
 "title": "4. Trident Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "taco_cluster", "label": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Trident POD Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CPU Usage ($taco_cluster)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{taco_cluster=~\"skb-suy-adm.*\",container=~\"trident.*\",namespace=~\"trident\",pod=~\"trident.*\"}[1m])) by (pod)\r",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage ($taco_cluster)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{taco_cluster=\"$taco_cluster\", container=~\"trident.*\",namespace=~\"trident\",pod=~\"trident.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "PV Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$taco_cluster : PV Usage (%) ",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes {taco_cluster=\"$taco_cluster\"} / kubelet_volume_stats_capacity_bytes {taco_cluster=\"$taco_cluster\"}) * 100 ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "NetApp Storage Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "NetApp Backend Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trident_core_backend_info{backend_type=\"ontap-nas\"}",
     "legendFormat": "{{backend_name}}:{{taco_cluster}}"
    }
   ]
  },
  {
   "title": "Average duration in ms of operations performed by Trident",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (operation) (trident_operation_duration_milliseconds_sum{success=\"true\"}) / sum by (operation) (trident_operation_duration_milliseconds_count{success=\"true\"})",
     "legendFormat": "{{ operation }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "# Volumes currently managed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 34 },
   "targets": [
    {
     "expr": "sort (trident_core_volume_count{taco_cluster=~\"skb.*\"} + on(backend_uuid) group_left(backend_name) trident_backend_info {taco_cluster=~\"skb.*\"})",
     "legendFormat": "{{ taco_cluster }}::{{ backend_name }}"
    }
   ]
  },
  {
   "title": "Capacity currently managed (GB)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 34 },
   "targets": [
    {
     "expr": "trident_core_volume_total_bytes / 1024 / 1024 / 1024",
     "legendFormat": "{{taco_cluster}}"
    }
   ]
  },
  {
   "title": "Number of volumes by Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trident_core_volume_count_by_backend",
     "legendFormat": "{{backend}}:{{taco_cluster}}"
    }
   ]
  },
  {
   "title": "Total Capacity by Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "trident_core_volume_total_bytes_by_backend / 1024 / 1024 / 1024",
     "legendFormat": "{{backend}}:{{taco_cluster}}"
    }
   ]
  },
  {
   "title": "Percentage of Failed HTTP responses ($taco_cluster)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "100-(sum (trident_rest_ops_seconds_total_count{taco_cluster=~\"$taco_cluster\", status_code=~\"2..\"} OR on() vector(0)) / sum (trident_rest_ops_seconds_total_count{taco_cluster=~\"$taco_cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Percentage of HTTP responses ($taco_cluster)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 51 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(sum (trident_rest_ops_seconds_total_count{taco_cluster=\"$taco_cluster\"}) by (status_code)  / scalar (sum (trident_rest_ops_seconds_total_count{taco_cluster=\"$taco_cluster\"}))) * 100",
     "legendFormat": "{{ status_code }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}